# Generated by Django 4.0.6 on 2022-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricks',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
