# Generated by Django 4.0.6 on 2022-07-22 12:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0002_rubricks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rubricks',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterField(
            model_name='rubricks',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фотографія'),
        ),
        migrations.AlterField(
            model_name='rubricks',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Імя'),
        ),
        migrations.AlterField(
            model_name='rubricks',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portfolio_project.rubricks', verbose_name='Наслідування'),
        ),
        migrations.AlterField(
            model_name='rubricks',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='слаг'),
        ),
    ]
