# Generated by Django 4.0.6 on 2022-07-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0003_tags_alter_rubricks_options_alter_rubricks_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Імя товару')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='слаг')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фотографія')),
                ('price', models.IntegerField(verbose_name='Ціна в гривнях')),
                ('avaibility', models.IntegerField(verbose_name='кількість на базі')),
                ('all_rating', models.IntegerField(verbose_name='Увесь рейтинг')),
                ('number_of_rating', models.IntegerField(verbose_name='кількість людей які поклали оцінку')),
                ('if_vip', models.BooleanField(default=False, verbose_name='ВІП')),
                ('rubrick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_project.rubricks')),
                ('tag', models.ManyToManyField(limit_choices_to=3, to='portfolio_project.tags', verbose_name='Фірми')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio_project.products', verbose_name='Імя продукту')),
            ],
            options={
                'verbose_name': 'Коментрії',
                'verbose_name_plural': 'Коментраіїї',
                'ordering': ['-created_at'],
            },
        ),
    ]
