# Generated by Django 4.0.6 on 2022-07-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0004_products_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rubrick',
            field=models.ForeignKey(blank=True, limit_choices_to=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubricks', to='portfolio_project.rubricks'),
        ),
    ]
