# Generated by Django 4.0.6 on 2022-07-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0007_products_describe_alter_products_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='avaibility',
        ),
    ]
