# Generated by Django 4.0.6 on 2022-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_project', '0008_remove_products_avaibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avaibility',
            field=models.BooleanField(default=True),
        ),
    ]
